// ABOUTME: Top-level Swift module for the Sprout mobile SDK.
// ABOUTME: Re-exports the UniFFI-generated bindings so downstream apps can `import SproutMobile`.

// The file `sprout_mobile.swift` is generated by uniffi-bindgen into this
// directory via `just mobile-swift-bindings`. It contains the Swift type
// wrappers around the Rust core. Because UniFFI puts its declarations at the
// top level of the containing module, importing SproutMobile exposes
// SproutClient, ClientConfig, UserIdentity, etc. directly.
//
// This file exists so the Swift Package has a non-empty target when the
// bindings file has not yet been generated (e.g. fresh checkout before
// running `just mobile-ios`).

@_exported import SproutCoreFFI
